### PR TITLE
Tried making theme more pervasive across the whole program + Semantic Highlighting™

### PR DESCRIPTION
**Pull request by redoxeon**
Started by trying to add #7 myself, but then decided to see if you all would be willing to add these extra tokens and UI colorizations? I really love this theme, and I tried to keep it as exactly the same as I could while using the scopes included with other more pervasive themes.

### CODE REVIEW

**Comment by redoxeon** [comment]
I should also note that this is only an update to the dark version of the theme. I don't feel that I have the skill/experience with light themes to make it look good (sorry).

**Comment by wuz** [comment]
@redoxeon this project kinda got lost for a bit, but I'm trying to pick it back up again - I'd love to merge this if that is still cool with you!

**Comment by redoxeon** [comment]
Absolutely! Let me know if there's changes you'd like me to make before you merge it ☺️

**Comment by wuz** [comment]
I think it looks solid! I'll merge now :)

**Pull request merged**
